language: java

# Compatibility tests to make sure API will not be deprecated
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

before_install:
 - chmod +x gradlew
 
install: ./gradlew build
